# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ResponseWindow(object):
    def setMatriz(self,matriz):
        self.matriz=matriz
        #set fila 1
        if matriz[0][0]==1:self.matriz_1_1.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[0][1]==1:self.matriz_1_2.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[0][2]==1:self.matriz_1_3.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[0][3]==1:self.matriz_1_4.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[0][4]==1:self.matriz_1_5.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[0][5]==1:self.matriz_1_6.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[0][6]==1:self.matriz_1_7.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[0][7]==1:self.matriz_1_8.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[0][8]==1:self.matriz_1_9.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[0][9]==1:self.matriz_1_10.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        #set fila 2
        if matriz[1][0]==1:self.matriz_2_1.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[1][1]==1:self.matriz_2_2.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[1][2]==1:self.matriz_2_3.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[1][3]==1:self.matriz_2_4.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[1][4]==1:self.matriz_2_5.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[1][5]==1:self.matriz_2_6.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[1][6]==1:self.matriz_2_7.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[1][7]==1:self.matriz_2_8.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[1][8]==1:self.matriz_2_9.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[1][9]==1:self.matriz_2_10.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        #set fila 3
        if matriz[2][0]==1:self.matriz_3_1.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[2][1]==1:self.matriz_3_2.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[2][2]==1:self.matriz_3_3.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[2][3]==1:self.matriz_3_4.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[2][4]==1:self.matriz_3_5.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[2][5]==1:self.matriz_3_6.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[2][6]==1:self.matriz_3_7.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[2][7]==1:self.matriz_3_8.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[2][8]==1:self.matriz_3_9.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[2][9]==1:self.matriz_3_10.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        #set fila 4
        if matriz[3][0]==1:self.matriz_4_1.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[3][1]==1:self.matriz_4_2.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[3][2]==1:self.matriz_4_3.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[3][3]==1:self.matriz_4_4.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[3][4]==1:self.matriz_4_5.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[3][5]==1:self.matriz_4_6.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[3][6]==1:self.matriz_4_7.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[3][7]==1:self.matriz_4_8.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[3][8]==1:self.matriz_4_9.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[3][9]==1:self.matriz_4_10.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        #set fila 5
        if matriz[4][0]==1:self.matriz_5_1.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[4][1]==1:self.matriz_5_2.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[4][2]==1:self.matriz_5_3.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[4][3]==1:self.matriz_5_4.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[4][4]==1:self.matriz_5_5.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[4][5]==1:self.matriz_5_6.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[4][6]==1:self.matriz_5_7.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[4][7]==1:self.matriz_5_8.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[4][8]==1:self.matriz_5_9.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[4][9]==1:self.matriz_5_10.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        #set fila 6
        if matriz[5][0]==1:self.matriz_6_1.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[5][1]==1:self.matriz_6_2.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[5][2]==1:self.matriz_6_3.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[5][3]==1:self.matriz_6_4.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[5][4]==1:self.matriz_6_5.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[5][5]==1:self.matriz_6_6.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[5][6]==1:self.matriz_6_7.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[5][7]==1:self.matriz_6_8.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[5][8]==1:self.matriz_6_9.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[5][9]==1:self.matriz_6_10.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        #set fila 7
        if matriz[6][0]==1:self.matriz_7_1.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[6][1]==1:self.matriz_7_2.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[6][2]==1:self.matriz_7_3.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[6][3]==1:self.matriz_7_4.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[6][4]==1:self.matriz_7_5.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[6][5]==1:self.matriz_7_6.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[6][6]==1:self.matriz_7_7.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[6][7]==1:self.matriz_7_8.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[6][8]==1:self.matriz_7_9.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[6][9]==1:self.matriz_7_10.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        #set fila 8
        if matriz[7][0]==1:self.matriz_8_1.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[7][1]==1:self.matriz_8_2.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[7][2]==1:self.matriz_8_3.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[7][3]==1:self.matriz_8_4.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[7][4]==1:self.matriz_8_5.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[7][5]==1:self.matriz_8_6.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[7][6]==1:self.matriz_8_7.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[7][7]==1:self.matriz_8_8.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[7][8]==1:self.matriz_8_9.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[7][9]==1:self.matriz_8_10.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        #set fila 9
        if matriz[8][0]==1:self.matriz_9_1.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[8][1]==1:self.matriz_9_2.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[8][2]==1:self.matriz_9_3.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[8][3]==1:self.matriz_9_4.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[8][4]==1:self.matriz_9_5.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[8][5]==1:self.matriz_9_6.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[8][6]==1:self.matriz_9_7.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[8][7]==1:self.matriz_9_8.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[8][8]==1:self.matriz_9_9.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[8][9]==1:self.matriz_9_10.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        #set fila 10
        if matriz[9][0]==1:self.matriz_10_1.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[9][1]==1:self.matriz_10_2.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[9][2]==1:self.matriz_10_3.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[9][3]==1:self.matriz_10_4.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[9][4]==1:self.matriz_10_5.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[9][5]==1:self.matriz_10_6.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[9][6]==1:self.matriz_10_7.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[9][7]==1:self.matriz_10_8.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[9][8]==1:self.matriz_10_9.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")
        if matriz[9][9]==1:self.matriz_10_10.setStyleSheet("background: url(:/prefijoNuevo/aerogenerador_resultado50.jpg);\n""background-position: center; \n""background-repeat: no-repeat;")

    def setupUi(self, ResponseWindow):
        ResponseWindow.setObjectName("ResponseWindow")
        ResponseWindow.resize(800, 650)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/prefijoNuevo/aerogeneradores.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ResponseWindow.setWindowIcon(icon)
        ResponseWindow.setStyleSheet("background: url(:/prefijoNuevo/aerogeneradores800.jpg);\n"
"")
        self.responseCentralwidget = QtWidgets.QWidget(ResponseWindow)
        self.responseCentralwidget.setStyleSheet("background-color:white;")
        self.responseCentralwidget.setObjectName("responseCentralwidget")
        #self.volver = QtWidgets.QPushButton(self.responseCentralwidget)
        #self.volver.setGeometry(QtCore.QRect(10, 2, 131, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        #self.volver.setFont(font)
        #self.volver.setStyleSheet("color:black;\n""background-color:green;")
        #self.volver.setAutoDefault(False)
        #self.volver.setObjectName("volver")
        self.resultados_titulo = QtWidgets.QLabel(self.responseCentralwidget)
        self.resultados_titulo.setGeometry(QtCore.QRect(280, 0, 241, 31))
        self.resultados_titulo.setStyleSheet("color:black;")
        self.resultados_titulo.setObjectName("resultados_titulo")
        self.matriz = None
        self.matriz_1_1 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_1_1.setGeometry(QtCore.QRect(100, 40, 60, 60))
        self.matriz_1_1.setStyleSheet("background:green;")
        self.matriz_1_1.setObjectName("matriz_1_1")
        self.matriz_2_1 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_2_1.setGeometry(QtCore.QRect(100, 100, 60, 60))
        self.matriz_2_1.setStyleSheet("background:green;")
        self.matriz_2_1.setObjectName("matriz_2_1")
        self.matriz_4_1 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_4_1.setGeometry(QtCore.QRect(100, 220, 60, 60))
        self.matriz_4_1.setStyleSheet("background:green;")
        self.matriz_4_1.setObjectName("matriz_4_1")
        self.matriz_3_1 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_3_1.setGeometry(QtCore.QRect(100, 160, 60, 60))
        self.matriz_3_1.setStyleSheet("background:green;")
        self.matriz_3_1.setObjectName("matriz_3_1")
        self.matriz_5_1 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_5_1.setGeometry(QtCore.QRect(100, 280, 60, 60))
        self.matriz_5_1.setStyleSheet("background:green;")
        self.matriz_5_1.setObjectName("matriz_5_1")
        self.matriz_6_1 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_6_1.setGeometry(QtCore.QRect(100, 340, 60, 60))
        self.matriz_6_1.setStyleSheet("background:green;")
        self.matriz_6_1.setObjectName("matriz_6_1")
        self.matriz_7_1 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_7_1.setGeometry(QtCore.QRect(100, 400, 60, 60))
        self.matriz_7_1.setStyleSheet("background:green;")
        self.matriz_7_1.setObjectName("matriz_7_1")
        self.matriz_8_1 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_8_1.setGeometry(QtCore.QRect(100, 460, 60, 60))
        self.matriz_8_1.setStyleSheet("background:green;")
        self.matriz_8_1.setObjectName("matriz_8_1")
        self.matriz_9_1 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_9_1.setGeometry(QtCore.QRect(100, 520, 60, 60))
        self.matriz_9_1.setStyleSheet("background:green;")
        self.matriz_9_1.setObjectName("matriz_9_1")
        self.matriz_10_1 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_10_1.setGeometry(QtCore.QRect(100, 580, 60, 60))
        self.matriz_10_1.setStyleSheet("background:green;")
        self.matriz_10_1.setObjectName("matriz_10_1")
        self.matriz_4_2 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_4_2.setGeometry(QtCore.QRect(160, 220, 60, 60))
        self.matriz_4_2.setStyleSheet("background:green;")
        self.matriz_4_2.setObjectName("matriz_4_2")
        self.matriz_6_2 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_6_2.setGeometry(QtCore.QRect(160, 340, 60, 60))
        self.matriz_6_2.setStyleSheet("background:green;")
        self.matriz_6_2.setObjectName("matriz_6_2")
        self.matriz_1_2 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_1_2.setGeometry(QtCore.QRect(160, 40, 60, 60))
        self.matriz_1_2.setStyleSheet("background:green;")
        self.matriz_1_2.setObjectName("matriz_1_2")
        self.matriz_2_2 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_2_2.setGeometry(QtCore.QRect(160, 100, 60, 60))
        self.matriz_2_2.setStyleSheet("background:green;")
        self.matriz_2_2.setObjectName("matriz_2_2")
        self.matriz_3_2 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_3_2.setGeometry(QtCore.QRect(160, 160, 60, 60))
        self.matriz_3_2.setStyleSheet("background:green;")
        self.matriz_3_2.setObjectName("matriz_3_2")
        self.matriz_10_2 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_10_2.setGeometry(QtCore.QRect(160, 580, 60, 60))
        self.matriz_10_2.setStyleSheet("background:green;")
        self.matriz_10_2.setObjectName("matriz_10_2")
        self.matriz_5_2 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_5_2.setGeometry(QtCore.QRect(160, 280, 60, 60))
        self.matriz_5_2.setStyleSheet("background:green;")
        self.matriz_5_2.setObjectName("matriz_5_2")
        self.matriz_8_2 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_8_2.setGeometry(QtCore.QRect(160, 460, 60, 60))
        self.matriz_8_2.setStyleSheet("background:green;")
        self.matriz_8_2.setObjectName("matriz_8_2")
        self.matriz_7_2 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_7_2.setGeometry(QtCore.QRect(160, 400, 60, 60))
        self.matriz_7_2.setStyleSheet("background:green;")
        self.matriz_7_2.setObjectName("matriz_7_2")
        self.matriz_9_2 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_9_2.setGeometry(QtCore.QRect(160, 520, 60, 60))
        self.matriz_9_2.setStyleSheet("background:green;")
        self.matriz_9_2.setObjectName("matriz_9_2")
        self.matriz_2_3 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_2_3.setGeometry(QtCore.QRect(220, 100, 60, 60))
        self.matriz_2_3.setStyleSheet("background:green;")
        self.matriz_2_3.setObjectName("matriz_2_3")
        self.matriz_7_3 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_7_3.setGeometry(QtCore.QRect(220, 400, 60, 60))
        self.matriz_7_3.setStyleSheet("background:green;")
        self.matriz_7_3.setObjectName("matriz_7_3")
        self.matriz_9_3 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_9_3.setGeometry(QtCore.QRect(220, 520, 60, 60))
        self.matriz_9_3.setStyleSheet("background:green;")
        self.matriz_9_3.setObjectName("matriz_9_3")
        self.matriz_10_3 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_10_3.setGeometry(QtCore.QRect(220, 580, 60, 60))
        self.matriz_10_3.setStyleSheet("background:green;")
        self.matriz_10_3.setObjectName("matriz_10_3")
        self.matriz_4_3 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_4_3.setGeometry(QtCore.QRect(220, 220, 60, 60))
        self.matriz_4_3.setStyleSheet("background:green;")
        self.matriz_4_3.setObjectName("matriz_4_3")
        self.matriz_1_3 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_1_3.setGeometry(QtCore.QRect(220, 40, 60, 60))
        self.matriz_1_3.setStyleSheet("background:green;")
        self.matriz_1_3.setObjectName("matriz_1_3")
        self.matriz_8_3 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_8_3.setGeometry(QtCore.QRect(220, 460, 60, 60))
        self.matriz_8_3.setStyleSheet("background:green;")
        self.matriz_8_3.setObjectName("matriz_8_3")
        self.matriz_10_4 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_10_4.setGeometry(QtCore.QRect(280, 580, 60, 60))
        self.matriz_10_4.setStyleSheet("background:green;")
        self.matriz_10_4.setObjectName("matriz_10_4")
        self.matriz_7_4 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_7_4.setGeometry(QtCore.QRect(280, 400, 60, 60))
        self.matriz_7_4.setStyleSheet("background:green;")
        self.matriz_7_4.setObjectName("matriz_7_4")
        self.matriz_1_4 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_1_4.setGeometry(QtCore.QRect(280, 40, 60, 60))
        self.matriz_1_4.setStyleSheet("background:green;")
        self.matriz_1_4.setObjectName("matriz_1_4")
        self.matriz_8_4 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_8_4.setGeometry(QtCore.QRect(280, 460, 60, 60))
        self.matriz_8_4.setStyleSheet("background:green;")
        self.matriz_8_4.setObjectName("matriz_8_4")
        self.matriz_2_4 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_2_4.setGeometry(QtCore.QRect(280, 100, 60, 60))
        self.matriz_2_4.setStyleSheet("background:green;")
        self.matriz_2_4.setObjectName("matriz_2_4")
        self.matriz_9_4 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_9_4.setGeometry(QtCore.QRect(280, 520, 60, 60))
        self.matriz_9_4.setStyleSheet("background:green;")
        self.matriz_9_4.setObjectName("matriz_9_4")
        self.matriz_1_5 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_1_5.setGeometry(QtCore.QRect(340, 40, 60, 60))
        self.matriz_1_5.setStyleSheet("background:green;")
        self.matriz_1_5.setObjectName("matriz_1_5")
        self.matriz_1_6 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_1_6.setGeometry(QtCore.QRect(400, 40, 60, 60))
        self.matriz_1_6.setStyleSheet("background:green;")
        self.matriz_1_6.setObjectName("matriz_1_6")
        self.matriz_1_7 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_1_7.setGeometry(QtCore.QRect(460, 40, 60, 60))
        self.matriz_1_7.setStyleSheet("background:green;")
        self.matriz_1_7.setObjectName("matriz_1_7")
        self.matriz_1_8 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_1_8.setGeometry(QtCore.QRect(520, 40, 60, 60))
        self.matriz_1_8.setStyleSheet("background:green;")
        self.matriz_1_8.setObjectName("matriz_1_8")
        self.matriz_1_9 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_1_9.setGeometry(QtCore.QRect(580, 40, 60, 60))
        self.matriz_1_9.setStyleSheet("background:green;")
        self.matriz_1_9.setObjectName("matriz_1_9")
        self.matriz_1_10 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_1_10.setGeometry(QtCore.QRect(640, 40, 60, 60))
        self.matriz_1_10.setStyleSheet("background:green;")
        self.matriz_1_10.setObjectName("matriz_1_10")
        self.matriz_2_5 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_2_5.setGeometry(QtCore.QRect(340, 100, 60, 60))
        self.matriz_2_5.setStyleSheet("background:green;")
        self.matriz_2_5.setObjectName("matriz_2_5")
        self.matriz_2_6 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_2_6.setGeometry(QtCore.QRect(400, 100, 60, 60))
        self.matriz_2_6.setStyleSheet("background:green;")
        self.matriz_2_6.setObjectName("matriz_2_6")
        self.matriz_2_7 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_2_7.setGeometry(QtCore.QRect(460, 100, 60, 60))
        self.matriz_2_7.setStyleSheet("background:green;")
        self.matriz_2_7.setObjectName("matriz_2_7")
        self.matriz_2_8 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_2_8.setGeometry(QtCore.QRect(520, 100, 60, 60))
        self.matriz_2_8.setStyleSheet("background:green;")
        self.matriz_2_8.setObjectName("matriz_2_8")
        self.matriz_2_9 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_2_9.setGeometry(QtCore.QRect(580, 100, 60, 60))
        self.matriz_2_9.setStyleSheet("background:green;")
        self.matriz_2_9.setObjectName("matriz_2_9")
        self.matriz_2_10 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_2_10.setGeometry(QtCore.QRect(640, 100, 60, 60))
        self.matriz_2_10.setStyleSheet("background:green;")
        self.matriz_2_10.setObjectName("matriz_2_10")
        self.matriz_3_3 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_3_3.setGeometry(QtCore.QRect(220, 160, 60, 60))
        self.matriz_3_3.setStyleSheet("background:green;")
        self.matriz_3_3.setObjectName("matriz_3_3")
        self.matriz_3_4 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_3_4.setGeometry(QtCore.QRect(280, 160, 60, 60))
        self.matriz_3_4.setStyleSheet("background:green;")
        self.matriz_3_4.setObjectName("matriz_3_4")
        self.matriz_3_5 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_3_5.setGeometry(QtCore.QRect(340, 160, 60, 60))
        self.matriz_3_5.setStyleSheet("background:green;")
        self.matriz_3_5.setObjectName("matriz_3_5")
        self.matriz_3_6 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_3_6.setGeometry(QtCore.QRect(400, 160, 60, 60))
        self.matriz_3_6.setStyleSheet("background:green;")
        self.matriz_3_6.setObjectName("matriz_3_6")
        self.matriz_3_7 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_3_7.setGeometry(QtCore.QRect(460, 160, 60, 60))
        self.matriz_3_7.setStyleSheet("background:green;")
        self.matriz_3_7.setObjectName("matriz_3_7")
        self.matriz_3_8 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_3_8.setGeometry(QtCore.QRect(520, 160, 60, 60))
        self.matriz_3_8.setStyleSheet("background:green;")
        self.matriz_3_8.setObjectName("matriz_3_8")
        self.matriz_3_9 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_3_9.setGeometry(QtCore.QRect(580, 160, 60, 60))
        self.matriz_3_9.setStyleSheet("background:green;")
        self.matriz_3_9.setObjectName("matriz_3_9")
        self.matriz_3_10 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_3_10.setGeometry(QtCore.QRect(640, 160, 60, 60))
        self.matriz_3_10.setStyleSheet("background:green;")
        self.matriz_3_10.setObjectName("matriz_3_10")
        self.matriz_4_4 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_4_4.setGeometry(QtCore.QRect(280, 220, 60, 60))
        self.matriz_4_4.setStyleSheet("background:green;")
        self.matriz_4_4.setObjectName("matriz_4_4")
        self.matriz_4_5 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_4_5.setGeometry(QtCore.QRect(340, 220, 60, 60))
        self.matriz_4_5.setStyleSheet("background:green;")
        self.matriz_4_5.setObjectName("matriz_4_5")
        self.matriz_4_6 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_4_6.setGeometry(QtCore.QRect(400, 220, 60, 60))
        self.matriz_4_6.setStyleSheet("background:green;")
        self.matriz_4_6.setObjectName("matriz_4_6")
        self.matriz_4_7 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_4_7.setGeometry(QtCore.QRect(460, 220, 60, 60))
        self.matriz_4_7.setStyleSheet("background:green;")
        self.matriz_4_7.setObjectName("matriz_4_7")
        self.matriz_4_8 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_4_8.setGeometry(QtCore.QRect(520, 220, 60, 60))
        self.matriz_4_8.setStyleSheet("background:green;")
        self.matriz_4_8.setObjectName("matriz_4_8")
        self.matriz_4_9 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_4_9.setGeometry(QtCore.QRect(580, 220, 60, 60))
        self.matriz_4_9.setStyleSheet("background:green;")
        self.matriz_4_9.setObjectName("matriz_4_9")
        self.matriz_4_10 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_4_10.setGeometry(QtCore.QRect(640, 220, 60, 60))
        self.matriz_4_10.setStyleSheet("background:green;")
        self.matriz_4_10.setObjectName("matriz_4_10")
        self.matriz_5_3 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_5_3.setGeometry(QtCore.QRect(220, 280, 60, 60))
        self.matriz_5_3.setStyleSheet("background:green;")
        self.matriz_5_3.setObjectName("matriz_5_3")
        self.matriz_5_4 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_5_4.setGeometry(QtCore.QRect(280, 280, 60, 60))
        self.matriz_5_4.setStyleSheet("background:green;")
        self.matriz_5_4.setObjectName("matriz_5_4")
        self.matriz_5_5 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_5_5.setGeometry(QtCore.QRect(340, 280, 60, 60))
        self.matriz_5_5.setStyleSheet("background:green;")
        self.matriz_5_5.setObjectName("matriz_5_5")
        self.matriz_5_6 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_5_6.setGeometry(QtCore.QRect(400, 280, 60, 60))
        self.matriz_5_6.setStyleSheet("background:green;")
        self.matriz_5_6.setObjectName("matriz_5_6")
        self.matriz_5_7 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_5_7.setGeometry(QtCore.QRect(460, 280, 60, 60))
        self.matriz_5_7.setStyleSheet("background:green;")
        self.matriz_5_7.setObjectName("matriz_5_7")
        self.matriz_5_8 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_5_8.setGeometry(QtCore.QRect(520, 280, 60, 60))
        self.matriz_5_8.setStyleSheet("background:green;")
        self.matriz_5_8.setObjectName("matriz_5_8")
        self.matriz_5_9 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_5_9.setGeometry(QtCore.QRect(580, 280, 60, 60))
        self.matriz_5_9.setStyleSheet("background:green;")
        self.matriz_5_9.setObjectName("matriz_5_9")
        self.matriz_5_10 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_5_10.setGeometry(QtCore.QRect(640, 280, 60, 60))
        self.matriz_5_10.setStyleSheet("background:green;")
        self.matriz_5_10.setObjectName("matriz_5_10")
        self.matriz_6_3 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_6_3.setGeometry(QtCore.QRect(220, 340, 60, 60))
        self.matriz_6_3.setStyleSheet("background:green;")
        self.matriz_6_3.setObjectName("matriz_6_3")
        self.matriz_6_4 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_6_4.setGeometry(QtCore.QRect(280, 340, 60, 60))
        self.matriz_6_4.setStyleSheet("background:green;")
        self.matriz_6_4.setObjectName("matriz_6_4")
        self.matriz_6_5 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_6_5.setGeometry(QtCore.QRect(340, 340, 60, 60))
        self.matriz_6_5.setStyleSheet("background:green;")
        self.matriz_6_5.setObjectName("matriz_6_5")
        self.matriz_6_6 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_6_6.setGeometry(QtCore.QRect(400, 340, 60, 60))
        self.matriz_6_6.setStyleSheet("background:green;")
        self.matriz_6_6.setObjectName("matriz_6_6")
        self.matriz_6_7 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_6_7.setGeometry(QtCore.QRect(460, 340, 60, 60))
        self.matriz_6_7.setStyleSheet("background:green;")
        self.matriz_6_7.setObjectName("matriz_6_7")
        self.matriz_6_8 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_6_8.setGeometry(QtCore.QRect(520, 340, 60, 60))
        self.matriz_6_8.setStyleSheet("background:green;")
        self.matriz_6_8.setObjectName("matriz_6_8")
        self.matriz_6_9 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_6_9.setGeometry(QtCore.QRect(580, 340, 60, 60))
        self.matriz_6_9.setStyleSheet("background:green;")
        self.matriz_6_9.setObjectName("matriz_6_9")
        self.matriz_6_10 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_6_10.setGeometry(QtCore.QRect(640, 340, 60, 60))
        self.matriz_6_10.setStyleSheet("background:green;")
        self.matriz_6_10.setObjectName("matriz_6_10")
        self.matriz_10_5 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_10_5.setGeometry(QtCore.QRect(340, 580, 60, 60))
        self.matriz_10_5.setStyleSheet("background:green;")
        self.matriz_10_5.setObjectName("matriz_10_5")
        self.matriz_8_5 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_8_5.setGeometry(QtCore.QRect(340, 460, 60, 60))
        self.matriz_8_5.setStyleSheet("background:green;")
        self.matriz_8_5.setObjectName("matriz_8_5")
        self.matriz_7_5 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_7_5.setGeometry(QtCore.QRect(340, 400, 60, 60))
        self.matriz_7_5.setStyleSheet("background:green;")
        self.matriz_7_5.setObjectName("matriz_7_5")
        self.matriz_9_5 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_9_5.setGeometry(QtCore.QRect(340, 520, 60, 60))
        self.matriz_9_5.setStyleSheet("background:green;")
        self.matriz_9_5.setObjectName("matriz_9_5")
        self.matriz_10_6 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_10_6.setGeometry(QtCore.QRect(400, 580, 60, 60))
        self.matriz_10_6.setStyleSheet("background:green;")
        self.matriz_10_6.setObjectName("matriz_10_6")
        self.matriz_8_6 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_8_6.setGeometry(QtCore.QRect(400, 460, 60, 60))
        self.matriz_8_6.setStyleSheet("background:green;")
        self.matriz_8_6.setObjectName("matriz_8_6")
        self.matriz_7_6 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_7_6.setGeometry(QtCore.QRect(400, 400, 60, 60))
        self.matriz_7_6.setStyleSheet("background:green;")
        self.matriz_7_6.setObjectName("matriz_7_6")
        self.matriz_9_6 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_9_6.setGeometry(QtCore.QRect(400, 520, 60, 60))
        self.matriz_9_6.setStyleSheet("background:green;")
        self.matriz_9_6.setObjectName("matriz_9_6")
        self.matriz_10_7 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_10_7.setGeometry(QtCore.QRect(460, 580, 60, 60))
        self.matriz_10_7.setStyleSheet("background:green;")
        self.matriz_10_7.setObjectName("matriz_10_7")
        self.matriz_8_7 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_8_7.setGeometry(QtCore.QRect(460, 460, 60, 60))
        self.matriz_8_7.setStyleSheet("background:green;")
        self.matriz_8_7.setObjectName("matriz_8_7")
        self.matriz_7_7 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_7_7.setGeometry(QtCore.QRect(460, 400, 60, 60))
        self.matriz_7_7.setStyleSheet("background:green;")
        self.matriz_7_7.setObjectName("matriz_7_7")
        self.matriz_9_7 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_9_7.setGeometry(QtCore.QRect(460, 520, 60, 60))
        self.matriz_9_7.setStyleSheet("background:green;")
        self.matriz_9_7.setObjectName("matriz_9_7")
        self.matriz_10_8 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_10_8.setGeometry(QtCore.QRect(520, 580, 60, 60))
        self.matriz_10_8.setStyleSheet("background:green;")
        self.matriz_10_8.setObjectName("matriz_10_8")
        self.matriz_8_8 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_8_8.setGeometry(QtCore.QRect(520, 460, 60, 60))
        self.matriz_8_8.setStyleSheet("background:green;")
        self.matriz_8_8.setObjectName("matriz_8_8")
        self.matriz_7_8 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_7_8.setGeometry(QtCore.QRect(520, 400, 60, 60))
        self.matriz_7_8.setStyleSheet("background:green;")
        self.matriz_7_8.setObjectName("matriz_7_8")
        self.matriz_9_8 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_9_8.setGeometry(QtCore.QRect(520, 520, 60, 60))
        self.matriz_9_8.setStyleSheet("background:green;")
        self.matriz_9_8.setObjectName("matriz_9_8")
        self.matriz_10_9 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_10_9.setGeometry(QtCore.QRect(580, 580, 60, 60))
        self.matriz_10_9.setStyleSheet("background:green;")
        self.matriz_10_9.setObjectName("matriz_10_9")
        self.matriz_8_9 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_8_9.setGeometry(QtCore.QRect(580, 460, 60, 60))
        self.matriz_8_9.setStyleSheet("background:green;")
        self.matriz_8_9.setObjectName("matriz_8_9")
        self.matriz_7_9 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_7_9.setGeometry(QtCore.QRect(580, 400, 60, 60))
        self.matriz_7_9.setStyleSheet("background:green;")
        self.matriz_7_9.setObjectName("matriz_7_9")
        self.matriz_9_9 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_9_9.setGeometry(QtCore.QRect(580, 520, 60, 60))
        self.matriz_9_9.setStyleSheet("background:green;")
        self.matriz_9_9.setObjectName("matriz_9_9")
        self.matriz_10_10 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_10_10.setGeometry(QtCore.QRect(640, 580, 60, 60))
        self.matriz_10_10.setStyleSheet("background:green;")
        self.matriz_10_10.setObjectName("matriz_10_10")
        self.matriz_8_10 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_8_10.setGeometry(QtCore.QRect(640, 460, 60, 60))
        self.matriz_8_10.setStyleSheet("background:green;")
        self.matriz_8_10.setObjectName("matriz_8_10")
        self.matriz_7_10 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_7_10.setGeometry(QtCore.QRect(640, 400, 60, 60))
        self.matriz_7_10.setStyleSheet("background:green;")
        self.matriz_7_10.setObjectName("matriz_7_10")
        self.matriz_9_10 = QtWidgets.QWidget(self.responseCentralwidget)
        self.matriz_9_10.setGeometry(QtCore.QRect(640, 520, 60, 60))
        self.matriz_9_10.setStyleSheet("background:green;")
        self.matriz_9_10.setObjectName("matriz_9_10")
        ResponseWindow.setCentralWidget(self.responseCentralwidget)

        self.retranslateUi(ResponseWindow)
        QtCore.QMetaObject.connectSlotsByName(ResponseWindow)

    def retranslateUi(self, ResponseWindow):
        _translate = QtCore.QCoreApplication.translate
        ResponseWindow.setWindowTitle(_translate("ResponseWindow", "Diseño Parque Eólico"))
        #self.volver.setText(_translate("ResponseWindow", "Volver"))
        self.resultados_titulo.setText(_translate("ResponseWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Diseño optimizado</span></p></body></html>"))
import img_rc
